language: ruby
rvm: 2.4.2

sudo: false
cache: bundler

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # speeds up installation of html-proofer

script:
- bundle exec jekyll build && bundle exec htmlproofer ./_site --check-html
